### ISSUE TITLE
Suggestion Change title color

### ISSUE THREAD

**Issue by Cmacdonald94** [Cmacdonald94/git-github-crash-course_02#1]
I think it looks better if the color is more red

```css
h1 {
  color: #ff0000;
}
```
